image: node:12.18.2-stretch

pipelines:
  branches:
    master:
      - step:
          script:
            - npm install -g gatsby-cli
            - npm install -g surge
            - rm -rf .cache
            - rm -rf public
            - rm -rf package-lock.json
            - rm -rf node_modules
            - npm install
            - npm run build
            - surge public modern-flock.surge.sh
